import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Footer from "../components/footer/Footer";
import Header3 from "../components/header/Header3";
import ConsultantMenu from "../components/consultant/ConsultantMenu";

function ConsultantLayout({ children }) {
  const currentPath = useRouter().pathname;
  return (
    <>
      <Head>
        <title>JOBES- Job Portal NextJs Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/assets/images/sm-logo.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header3 />
      <div className="dashboard-area company-dashboard pt-30 mb-120">
        <div className="container">
          <div className="row g-4">
            <ConsultantMenu />
            {children}
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}

export default ConsultantLayout;
